// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZdg_STjxl3CUFvhQxFnPinK3R6_PFJsc',
    appId: '1:858164631228:web:XXXXXXXXXXXXXXXXXXXXXXXX',
    messagingSenderId: '858164631228',
    projectId: 'trends-cd27d',
    authDomain: 'trends-cd27d.firebaseapp.com',
    storageBucket: 'trends-cd27d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZdg_STjxl3CUFvhQxFnPinK3R6_PFJsc',
    appId: '1:858164631228:android:2a3659018a433ba1ad62b9',
    messagingSenderId: '858164631228',
    projectId: 'trends-cd27d',
    storageBucket: 'trends-cd27d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZdg_STjxl3CUFvhQxFnPinK3R6_PFJsc',
    appId: '1:858164631228:ios:XXXXXXXXXXXXXXXXXXXXXXXX',
    messagingSenderId: '858164631228',
    projectId: 'trends-cd27d',
    storageBucket: 'trends-cd27d.firebasestorage.app',
    iosBundleId: 'com.rektech.trends',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZdg_STjxl3CUFvhQxFnPinK3R6_PFJsc',
    appId: '1:858164631228:ios:XXXXXXXXXXXXXXXXXXXXXXXX',
    messagingSenderId: '858164631228',
    projectId: 'trends-cd27d',
    storageBucket: 'trends-cd27d.firebasestorage.app',
    iosBundleId: 'com.rektech.trends',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZdg_STjxl3CUFvhQxFnPinK3R6_PFJsc',
    appId: '1:858164631228:web:XXXXXXXXXXXXXXXXXXXXXXXX',
    messagingSenderId: '858164631228',
    projectId: 'trends-cd27d',
    authDomain: 'trends-cd27d.firebaseapp.com',
    storageBucket: 'trends-cd27d.firebasestorage.app',
  );
}
